version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - REDIS_HOST=redis
      - L5_SWAGGER_USE_ABSOLUTE_PATH=false
      - L5_SWAGGER_CONST_HOST=https://node42.webte.fei.stuba.sk
      - L5_SWAGGER_BASE_PATH=/zz/api
      - APP_TRUST_PROXIES=*
      - ASSET_URL=https://node42.webte.fei.stuba.sk
    depends_on:
      - redis
      - mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    networks:
      - app-network

  mysql:
    image: mariadb:10                        
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql        
    networks:
      - app-network    

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_API_BASE_URL: /zz/api
    ports:
      - "127.0.0.1:9001:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge